### ISSUE TITLE
"tickshift"

### ISSUE THREAD

**Issue by HausemasterIssue** [noatmc-archived/timer-but-really-bad#6]
OMG ITS TICKSHIFT FROM FUTURE BETA!!!!!!!!!!!!!!!!

literally just timer but it autodisables after like 0.1 seconds bro, i could make that shit in literally 5 seconds

**Comment by noatmc-archived** [comment]
👍

**Comment by arjunnain17** [comment]
that's literally what tickshift does dumbass

**Comment by arjunnain17** [comment]
> literally just timer but it autodisables after like 0.1 seconds bro, i could make that shit in literally 5 seconds

then why didnt you make it

**Comment by HausemasterIssue** [comment]
yours dosen't even do what i said roflsauce

**Comment by noatmc-archived** [comment]
chill

**Comment by HausemasterIssue** [comment]
fixed ur code in pr 🦍

**Comment by ZenovJB** [comment]
> that's literally what tickshift does dumbass

stop baiting me
